// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabasUppgiftEntity.Models;

public partial class Course
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? EmployeeId { get; set; }

    public bool? Active { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();
}