// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabasUppgiftEntity.Models;

public partial class Grade
{
    public int Id { get; set; }

    public int StudentId { get; set; }

    public int EmployeeId { get; set; }

    public int CourseId { get; set; }

    public string GradeValue { get; set; }

    public DateOnly DateAssigned { get; set; }

    public virtual Course Course { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Student Student { get; set; }
}