// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabasUppgiftEntity.Models;

public partial class Student
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string PersonalNumber { get; set; }

    public string ClassName { get; set; }

    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();
}